name: Nature Music Fix Automation

on:
  schedule:
    - cron: '30 0,3,6,9 * * *' # 6AM, 9AM, 12PM, 3PM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Tools
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install requests moviepy==1.0.3 decorator==4.4.2
      - name: Run
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          FREESOUND_API_KEY: ${{ secrets.FREESOUND_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: python main.py
      - name: Save
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Bot"
          git add posted_videos.txt
          git commit -m "sync" || echo "no"
          git push
