name: Pure Nature Fixed Final

on:
  schedule:
    # 6AM, 9AM, 12PM, 3PM IST
    - cron: '30 0,3,6,9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: checkout@v3

      - name: Setup Python
        uses: setup-python@v4
        with:
          python-version: '3.9'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python Packages
        run: |
          pip install requests
          pip install moviepy==1.0.3 # Error fix karne ke liye stable version use karein

      - name: Run
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
        run: python main.py

      - name: Sync History
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Bot"
          git add posted_videos.txt
          git commit -m "update" || echo "no changes"
          git push
